- README.md
- src/chains.ts
- wagmi.config.ts
> docs: add disclaimer to README; remove arb one addresses

- src/chains.ts
- src/createRollupFetchTransactionHash.ts
- src/prepareNodeConfig.ts
- wagmi.config.ts
Adds Ethereum Mainnet and Arbitrum One contracts and updates TokenBridgeCreator addresses to v1.2.0.
> feat: update contracts

- src/chains.ts
- src/createRollupFetchTransactionHash.ts
- src/generated.ts
- src/prepareNodeConfig.ts
- wagmi.config.ts
> feat: add holesky factory contracts

- wagmi.config.ts
output looks like this now and is quicker due to reduced sleep
```
$ wagmi generate
Checking if contracts match by comparing hashed JSON ABIs.
- RollupCreator
- 0x308d5054427fad7c8621824a7668a375cce543a82f854e29ece132c3781901d6 (42161)
- 0x308d5054427fad7c8621824a7668a375cce543a82f854e29ece132c3781901d6 (17000)
- 0x308d5054427fad7c8621824a7668a375cce543a82f854e29ece132c3781901d6 (11155111)
- 0x308d5054427fad7c8621824a7668a375cce543a82f854e29ece132c3781901d6 (42170)
- 0x308d5054427fad7c8621824a7668a375cce543a82f854e29ece132c3781901d6 (421614)
- 0x308d5054427fad7c8621824a7668a375cce543a82f854e29ece132c3781901d6 (1)
- RollupCreator ✔
- TokenBridgeCreator
- 0xd707b9deb446e327b8658e1f62c5d8b87aea3edc23e2fc760a09d0fa3349e7c7 (1)
- 0xd707b9deb446e327b8658e1f62c5d8b87aea3edc23e2fc760a09d0fa3349e7c …
```
> chore: make generate output nicer

- src/utils/getArbOSVersion.ts
- src/utils/getArbOSVersion.unit.test.ts
> feat: Add getArbOSVersion util

- src/utils/getClientVersion.ts
- src/utils/getClientVersion.unit.test.ts
- src/utils/index.ts
> feat: add util for fetching client version

- .github/workflows/build-test.yml
- .github/workflows/check-pr-title.yml
New workflow will cancel previous workflow for a given PR
closes fs-481
> ci: cancel in progress workflows

- src/arbAggregatorPrepareTransactionRequest.ts
- src/arbAggregatorReadContract.ts
- src/contracts.ts
- src/decorators/arbAggregatorActions.integration.test.ts
- src/decorators/arbAggregatorActions.ts
- src/generated.ts
- src/index.ts
- wagmi.config.ts
This PR adds a decorator to use the ArbAggregator precompile
> feat: add ArbAggregator decorator

- src/abi/index.ts
- src/contracts.ts
- src/index.ts
- src/utils/index.ts
Add utils exports:
- getRollupCreatorAddress
- getTokenBridgeCreatorAddress
Add contract export:
- rollupAdminLogic
Closes FS-522
> feat: update exports

- src/createRollupFetchTransactionHash.ts
https://sepolia.etherscan.io/address/0xfbd0b034e6305788007f6e0123cc5eae701a5751
> fix: update holesky rollup creator deployment block

- src/upgradeExecutorPrepareAddExecutorTransactionRequest.ts
- src/upgradeExecutorPrepareRemoveExecutorTransactionRequest.ts
- src/utils/assertChainId.ts
Add assertChainId to get chainId from publicClient
Closes fs-588
> fix: Remove validateChain in upgradeExecutor utils

- src/index.ts
- src/upgradeExecutorEncodeFunctionData.ts
> chore: Export upgrade executor roles

- package.json
- yarn.lock
> fix: Bump ws versions

- src/index.ts
- src/isAnyTrust.ts
- src/isAnyTrust.unit.test.ts
> feat: add isAnyTrust

- src/actions/getAllChainOwners.ts
- src/actions/getInfraFeeAccount.ts
- src/actions/getNetworkFeeAccount.ts
- src/actions/getScheduledUpgrade.ts
- src/actions/isChainOwner.ts
> feat: Add v1 ArbOwnerPublic getters

- src/actions/addChainOwner.ts
- src/actions/removeChainOwner.ts
- src/actions/setMaxTxGasLimit.ts
- src/actions/setParentPricePerUnit.ts
- src/actions/setParentPricingRewardRate.ts
- src/actions/setParentPricingRewardRecipient.ts
- src/actions/setSpeedLimit.ts
> feat: Add v1 ArbOwnerPublic setters

- src/createTokenBridge-ethers.ts
Closes https://github.com/OffchainLabs/arbitrum-orbit-sdk/issues/157
> fix: convert big number to hex string first

- src/index.ts
- src/wasmModuleRoot.ts
> feat: add getConsensusVersion util

- src/package.json
> fix: properly export contracts

- src/createTokenBridge-ethers.ts
Everything stays exactly the same except `maxSubmissionCost` and `maxGas` for factory deployment are both returned from the function.
> refactor: move code to fn for factory gas estimation

- src/createRollupGetRetryablesFees.ts
- src/createTokenBridge-ethers.ts
- src/createTokenBridgePrepareCustomFeeTokenApprovalTransactionRequest.ts
- src/createTokenBridgePrepareTransactionRequest.ts
> feat: improve retryables gas estimation

- src/createRollupFetchTransactionHash.ts
- src/getBatchPosters.ts
- src/getBatchPosters.unit.test.ts
- src/getKeysets.ts
- src/getValidators.ts
- src/isAnyTrust.ts
- src/utils/getEarliestRollupCreatorDeploymentBlockNumber.ts
- src/utils/getLogsWithBatching.integration.test.ts
- src/utils/getLogsWithBatching.ts
- src/utils/getLogsWithBatching.unit.test.ts
> feat: batch long-range log queries

- src/createRollupFetchTransactionHash.ts
Closes https://github.com/OffchainLabs/arbitrum-orbit-sdk/issues/205.
> feat: enable fromBlock override in rollup tx fetch

- src/contracts/RollupCreator/v2.1.ts
- src/utils/getRollupCreatorAddress.unit.test.ts
- wagmi.config.ts
> feat: update nitro contracts to v2.1.3

- examples/setup-aep-fee-router/README.md
> docs: Update README.md

- examples/setup-aep-fee-router/.env.example
- examples/setup-aep-fee-router/README.md
- examples/setup-aep-fee-router/index.ts
- Add optional env vars to specify custom recipients for each fee type
- Always deploy separate RewardDistributor for each fee collector
- Update README to reflect new functionality
> feat: add custom recipient support for fee distributors
