OffchainLabs/arbitrum-orbit-sdk

- examples/eth/index.ts
Because we just have Arb Sepolia and Sepolia chains defined for rollup creation, Arb Goerli txs would be rejected so this script can't be executed. I've decided to change it to Arb Sepolia and not adding Arb Goerli to the chain list cause Arb Goerli is going to be depreciated.
> changing arb goerli to arb sepolia

- src/createRollup.integration.test.ts
- src/createRollup.ts
- src/createRollupPrepareTransactionRequest.ts
The function `createRollupGetCallValue` was being called without applying defaults, which means `params.deployFactoriesToL2` was set to `false` (even though are defaults set it to `true`) so the call value was always 0. 
Now we properly apply defaults to input params first.
I also added one extra assertion to make sure everything was executed properly and the logs can be successfully decoded.
The test failing in CI should be ignored as it's not set up properly, and should be tried out locally.
> fix: properly set callvalue in create rollup

- .github/workflows/build-test.yml
- wagmi.config.ts
Fixes argument `ref` to `nitro-testnode-ref` and adds the following flags:
```
// RollupCreator on L1 is deployed by default
--tokenbridge // this will make sure we have the TokenBridgeCreator deployed on L1
--l3node // this will make sure we have RollupCreator deployed on L2
--l3-token-bridge // this will make sure we have TokenBridgeCreator deployed on L2
```
> ci: update nitro-testnode params

- examples/verify-rollup/.env.example
- examples/verify-rollup/src/lib/client.ts
- examples/verify-rollup/src/lib/utils.ts
- examples/verify-rollup/src/verify-rollup.ts
When using the public RPC for Sepolia or Ethereum mainnet, the query to search for events might take too long and the request might timeout.
This is a temporary patch that allows a custom RPC to be specified which will perform these searches faster.
The solution to the problem, however, is to somehow restrict the range of blocks to search events on. This patch will allow clients to continue using the verification script in the short term.
This PR also fixes one bug that breaks the script when getting admins of contracts that have leading 0s in them.
> fix: allow custom parent chain RPC (and fix bug)

- src/prepareNodeConfig.ts
- src/types/NodeConfig.ts
This PR adds one more parameter to the node configuration. Since we are using the fast-deposit configuration parameters, we can reduce the number of blocks the chain waits for finalization to 1 (instead of the default 20).
> feat: reduce default finalize distance

- src/decorators/rollupAdminLogicActions.unit.test.ts
- src/decorators/rollupAdminLogicPublicActions.integration.test.ts
- src/decorators/rollupAdminLogicPublicActions.ts
Allow user to pass an address to override the rollup address passed when creating the actions.
Add unit test.
closes FS-514
> fix: allow rollup address override

- src/__snapshots__/createRollupPrepareConfig.unit.test.ts.snap
- src/createRollupPrepareConfig.ts
- src/createRollupPrepareConfig.unit.test.ts
This PR:
- fixes the type for arguments to `createRollupPrepareConfig`
Problem was there was a typo:
```
Partial<Omit<CreateRollupPrepareConfigResult | 'chainConfig', RequiredKeys>>
```
but the correct way is:
```
Partial<Omit<CreateRollupPrepareConfigResult, 'chainConfig' | RequiredKeys>>;
```
- adds tests (will be useful for next set of PRs to make sure we don't break things)
Closes FS-551.
> fix: properly type `createRollupPrepareConfig` args

- src/parentChainIsArbitrum.ts
- src/prepareNodeConfig.ts
Cleaning a few things up so I can revive https://github.com/OffchainLabs/arbitrum-orbit-sdk/pull/55
> refactor: move `parentChainIsArbitrum` to separate file

- src/utils/getArbOSVersion.unit.test.ts
Mainnet can take long time on CI (~50s in worst case), Sepolia seems to be fine on CI
> test: Change chain for getArbOsVersion unit test

- src/actions/setConfirmPeriodBlocks.ts
- src/actions/setExtraChallengeTimeBlocks.ts
- src/actions/setMinimumAssertionPeriod.ts
- src/actions/setValidator.ts
- src/actions/setValidatorWhitelistDisabled.ts
- src/actions/setWasmModuleRoot.ts
> feat: Add v1 RollupAdminLogic setters

- src/actions/hasRole.ts
> feat: Add v1 upgradeExecutor getters

- src/actions/addExecutor.ts
- src/actions/removeExecutor.ts
> feat: Add v1 upgradeExecutor setters

- src/chains.ts
- src/decorators/__snapshots__/publicActionsChildChain.unit.test.ts.snap
- src/decorators/publicActionsChildChain.ts
- src/decorators/publicActionsChildChain.unit.test.ts
- src/decorators/publicActionsParentChain.ts
- src/decorators/publicActionsParentChain.unit.test.ts
> feat: Add v1 publicActionsChildChain

- src/createRollupPrepareDeploymentParamsConfigDefaults.ts
- src/index.ts
- src/wasmModuleRoot.ts
The original approach made sense when the only info on the consensus release was `wasmModuleRoot`. In a future PR, I'll be adding `maxSupportedArbOSVersion` to each consensus release for extra validation, so having utils to return the whole object instead of just a single property makes more sense for future-proofing.
> feat: update wasm utils as consensus release utils

- examples/setup-fast-withdrawal/index.ts
When running the setup-fast-withdrawal script, the fastConfirmer is not added to the validator whitelist, and thus can't fastConfirm any node (the caller needs to be a validator too).
This PR fixes that.
> fix: add fastConfirmer to the validator list

- examples/setup-aep-fee-router/index.ts
- src/feeRouterDeployChildToParentRewardRouter.ts
This PR fixes a small bug where the function feeRouterDeployChildToParentRewardRouter uses the wrong router based on the client used. Since it makes more sense to use the parent chain client, the parent chain router is used now.
> fix: use proper router for ChildToParentRewardRouter

- examples/setup-aep-fee-router/.env.example
- examples/setup-aep-fee-router/README.md
This PR updates the information in the README of the AEP setup script
> chore: update aep setup script readme

- src/getValidators.ts
- src/getValidators.unit.test.ts
Looks like the Xai team used [MultiSend](https://github.com/safe-global/safe-smart-account/blob/main/contracts/libraries/MultiSend.sol) to do multiple calls to the UpgradeExecutor in a single transaction.
We currently don't support decoding MultiSend calls, so it was throwing an error.
For now, I handled it so we explicitly only support inner call directly to UpgradeExecutor, and I'll track supporting other signatures in another ticket.
> fix: handle unknown Safe call in getValidators

- src/createRollupFetchCoreContracts.ts
- src/createTokenBridge.ts
- src/createTokenBridgePrepareSetWethGatewayTransactionRequest.ts
Closes https://github.com/OffchainLabs/arbitrum-orbit-sdk/issues/233.
> feat: accept rollup deployment block number for query

- package.json
- yarn.lock
Resolves this advisory https://github.com/advisories/GHSA-vjh7-7g9h-fjfh
> build(deps): bump elliptic from 6.5.7 to 6.6.1
